In [2]:
import numpy as np

In [3]:
# Tensors definition.

# 0D tensor = scalar tensor

x = np.array(12)
x

array(12)

In [4]:
x.ndim

0

In [5]:
x.dtype

dtype('int32')

In [6]:
y = np.array(12.5)
y

array(12.5)

In [7]:
y.dtype

dtype('float64')

In [8]:
# 1D tensor = vector 

# This vector 'a' has 5 items.
a = np.array([12, 3, 6, 14, 7])
a

array([12,  3,  6, 14,  7])

In [9]:
a.ndim

1

In [10]:
a.dtype

dtype('int32')

In [13]:
# 2D tensor = matrix

# This matrix's shape is (3, 5). Number of rows and columns.
b = np.array([[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]])
b

array([[ 5, 78,  2, 34,  0],
       [ 6, 79,  3, 35,  1],
       [ 7, 80,  4, 36,  2]])

In [14]:
b.ndim

2

In [15]:
b.shape

(3, 5)

In [16]:
b.dtype

dtype('int32')

In [17]:
# 3D tensor 

# This 3D tensor's shape is (3, 3, 5). Number of matrices, number of rows in one matrix and number of columns in one matrix. 
c = np.array([[[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]]])
c

array([[[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]]])

In [18]:
c.ndim

3

In [19]:
c.shape

(3, 3, 5)

In [20]:
c.dtype

dtype('int32')

In [21]:
# 4D tensor 

"""
This 4D tensor's shape is (4, 2, 3, 4). 4 is number of groups,
                                        2 is number of matrices inside one group,
                                        3 is number of rows in one matrix,
                                        4 is number of columns in one matrix.
"""

d = np.array(
    [
        [
                [ [5, 78, 2, 34],
                  [6, 79, 3, 35],
                  [7, 80, 4, 36] ],
                [ [5, 78, 2, 34],
                  [6, 79, 3, 35],
                  [7, 80, 4, 36] ]
        ],
        
        [
                [ [5, 78, 2, 34],
                  [6, 79, 3, 35],
                  [7, 80, 4, 36] ],
                [ [5, 78, 2, 34],
                  [6, 79, 3, 35],
                  [7, 80, 4, 36] ]
        ],
        
        [
                [ [5, 78, 2, 34],
                  [6, 79, 3, 35],
                  [7, 80, 4, 36] ],
                [ [5, 78, 2, 34],
                  [6, 79, 3, 35],
                  [7, 80, 4, 36] ]
        ],
        
        [
                [ [5, 78, 2, 34],
                  [6, 79, 3, 35],
                  [7, 80, 4, 36] ],
                [ [5, 78, 2, 34],
                  [6, 79, 3, 35],
                  [7, 80, 4, 36] ]
        ]
    ]
)

d

array([[[[ 5, 78,  2, 34],
         [ 6, 79,  3, 35],
         [ 7, 80,  4, 36]],

        [[ 5, 78,  2, 34],
         [ 6, 79,  3, 35],
         [ 7, 80,  4, 36]]],


       [[[ 5, 78,  2, 34],
         [ 6, 79,  3, 35],
         [ 7, 80,  4, 36]],

        [[ 5, 78,  2, 34],
         [ 6, 79,  3, 35],
         [ 7, 80,  4, 36]]],


       [[[ 5, 78,  2, 34],
         [ 6, 79,  3, 35],
         [ 7, 80,  4, 36]],

        [[ 5, 78,  2, 34],
         [ 6, 79,  3, 35],
         [ 7, 80,  4, 36]]],


       [[[ 5, 78,  2, 34],
         [ 6, 79,  3, 35],
         [ 7, 80,  4, 36]],

        [[ 5, 78,  2, 34],
         [ 6, 79,  3, 35],
         [ 7, 80,  4, 36]]]])

In [22]:
d.ndim

4

In [23]:
d.shape

(4, 2, 3, 4)

In [24]:
d.dtype

dtype('int32')